/**
 * Error type enumeration for the application
 */
export enum ErrorType {
  ZOTERO_ERROR = "ZOTERO_ERROR",
  API_ERROR = "API_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  FILE_ERROR = "FILE_ERROR",
  METADATA_ERROR = "METADATA_ERROR",
  DOWNLOAD_ERROR = "DOWNLOAD_ERROR",
  RATE_LIMIT = "RATE_LIMIT",
  TIMEOUT = "TIMEOUT",
  UNKNOWN = "UNKNOWN",
}
