// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "email": string;
      "coreApiKey": string;
      "scihub.enabled": boolean;
      "scihub.maxErrors": number;
      "updateExistingMetadata": boolean;
      "autoDownloadOnAdd": boolean;
      "autoretrieve": string;
      "tag_nopdf": string;
      "tag_haspdf": string;
      "downloadTimeout": number;
      "maxRetries": number;
      "debug": boolean;
    };
  }
}
