// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "extensions.zotadata.unpaywallEmail": string;
      "extensions.zotadata.coreApiKey": string;
      "extensions.zotadata.updateExistingMetadata": boolean;
      "extensions.zotadata.autoDownloadOnAdd": boolean;
      "extensions.zotadata.debug": boolean;
      "extensions.zotadata.email": string;
      "extensions.zotadata.autoretrieve": string;
      "extensions.zotadata.tag_nopdf": string;
      "extensions.zotadata.tag_haspdf": string;
      "extensions.zotadata.downloadTimeout": number;
      "extensions.zotadata.maxRetries": number;
    };
  }
}
