name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate version format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9-]+)?$ ]]; then
            echo "Error: Version must follow semantic versioning (e.g., 1.0.0 or 1.0.0-beta)"
            exit 1
          fi
          
      - name: Build XPI
        run: |
          chmod +x zotadata/build.sh
          cd zotadata
          ./build.sh ${{ inputs.version }}
          
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: Release v${{ inputs.version }}
          body: |
            ## Zotero Zotadata v${{ inputs.version }}
            
            ### Installation
            1. Download the XPI file below
            2. Open Zotero 7
            3. Go to Tools → Add-ons
            4. Click gear icon → Install Add-on From File...
            5. Select the downloaded XPI file
            6. Restart Zotero
            
            ### Compatibility
            - Zotero 7.x only
          draft: false
          prerelease: ${{ contains(inputs.version, '-') }}
          
      - name: Upload XPI Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zotadata/zotero-zotadata-${{ inputs.version }}.xpi
          asset_name: zotero-zotadata-${{ inputs.version }}.xpi
          asset_content_type: application/zip 